// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalsaSimulator.Data;

#nullable disable

namespace SalsaSimulator.Migrations
{
    [DbContext(typeof(SalsaDbContext))]
    partial class SalsaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("SalsaSimulator.Models.Aji", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Ahumado")
                        .HasColumnType("REAL");

                    b.Property<string>("AporteSalsa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorPrincipal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CombinaCon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Complejidad")
                        .HasColumnType("REAL");

                    b.Property<string>("DificultadConseguir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Dulzor")
                        .HasColumnType("REAL");

                    b.Property<bool>("FermentaBien")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Frescura")
                        .HasColumnType("REAL");

                    b.Property<double>("Frutalidad")
                        .HasColumnType("REAL");

                    b.Property<string>("FuncionIdeal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NotasAromaticas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaisRegion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PerfilSabor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Persistencia")
                        .HasColumnType("REAL");

                    b.Property<double>("Picante")
                        .HasColumnType("REAL");

                    b.Property<string>("RiesgoDominar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScovilleEstimado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ajies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ahumado = 2.0,
                            AporteSalsa = "Frescura y picante base; excelente equilibrio",
                            ColorPrincipal = "Verde brillante",
                            CombinaCon = "Ajo, cilantro, limón, serrano, cebolla",
                            Complejidad = 5.0,
                            DificultadConseguir = "Fácil",
                            Dulzor = 3.0,
                            FermentaBien = true,
                            Frescura = 9.0,
                            Frutalidad = 4.0,
                            FuncionIdeal = "Base / Personalidad",
                            Nombre = "Jalapeño",
                            NotasAromaticas = "Hierba fresca, verde, pimiento",
                            PaisRegion = "México",
                            PerfilSabor = "Verde fresco, herbáceo, vegetal con toque de calor moderado",
                            Persistencia = 4.0,
                            Picante = 4.0,
                            RiesgoDominar = "Bajo",
                            ScovilleEstimado = "2,500–8,000"
                        },
                        new
                        {
                            Id = 2,
                            Ahumado = 1.0,
                            AporteSalsa = "Picante limpio y fresco, estructura vegetal",
                            ColorPrincipal = "Verde oscuro",
                            CombinaCon = "Jalapeño, tomatillo, cilantro, ajo",
                            Complejidad = 5.0,
                            DificultadConseguir = "Fácil",
                            Dulzor = 2.0,
                            FermentaBien = true,
                            Frescura = 9.0,
                            Frutalidad = 3.0,
                            FuncionIdeal = "Picante / Base",
                            Nombre = "Serrano",
                            NotasAromaticas = "Verde intenso, herbáceo, limpio",
                            PaisRegion = "México",
                            PerfilSabor = "Más intenso que jalapeño, limpio, fresco, ligeramente ácido",
                            Persistencia = 5.0,
                            Picante = 5.0,
                            RiesgoDominar = "Bajo",
                            ScovilleEstimado = "10,000–23,000"
                        },
                        new
                        {
                            Id = 3,
                            Ahumado = 1.0,
                            AporteSalsa = "Picante universal, fondo seco, sin complejidad dominante",
                            ColorPrincipal = "Rojo brillante",
                            CombinaCon = "Casi todo; ajo, vinagre, tomate",
                            Complejidad = 4.0,
                            DificultadConseguir = "Fácil",
                            Dulzor = 2.0,
                            FermentaBien = true,
                            Frescura = 5.0,
                            Frutalidad = 2.0,
                            FuncionIdeal = "Picante",
                            Nombre = "Cayena / Cayenne",
                            NotasAromaticas = "Terroso, seco, levemente frutal",
                            PaisRegion = "América del Sur",
                            PerfilSabor = "Picante directo y limpio, algo terroso, moderado aroma",
                            Persistencia = 6.0,
                            Picante = 6.0,
                            RiesgoDominar = "Medio-bajo",
                            ScovilleEstimado = "30,000–50,000"
                        },
                        new
                        {
                            Id = 4,
                            Ahumado = 1.0,
                            AporteSalsa = "Carácter tropical poderoso; el rey del sabor habanero",
                            ColorPrincipal = "Naranja/Rojo",
                            CombinaCon = "Mango, piña, cítrico, zanahoria, ajo",
                            Complejidad = 9.0,
                            DificultadConseguir = "Fácil",
                            Dulzor = 6.0,
                            FermentaBien = true,
                            Frescura = 4.0,
                            Frutalidad = 9.0,
                            FuncionIdeal = "Personalidad / Picante",
                            Nombre = "Habanero",
                            NotasAromaticas = "Floral intenso, mango, cítrico, tropical",
                            PaisRegion = "Caribe/México",
                            PerfilSabor = "Explosivo, tropical, floral, cítrico, fruta de la pasión",
                            Persistencia = 9.0,
                            Picante = 8.0,
                            RiesgoDominar = "Alto",
                            ScovilleEstimado = "100,000–350,000"
                        },
                        new
                        {
                            Id = 5,
                            Ahumado = 1.0,
                            AporteSalsa = "Sabor caribeño profundo, dulzor y fuego a la vez",
                            ColorPrincipal = "Naranja/Amarillo",
                            CombinaCon = "Mango, coco, jengibre, ajo, cebolla",
                            Complejidad = 9.0,
                            DificultadConseguir = "Media",
                            Dulzor = 7.0,
                            FermentaBien = true,
                            Frescura = 4.0,
                            Frutalidad = 9.0,
                            FuncionIdeal = "Personalidad",
                            Nombre = "Scotch Bonnet",
                            NotasAromaticas = "Fruta tropical, floral dulce, algo terroso",
                            PaisRegion = "Caribe",
                            PerfilSabor = "Similar habanero pero más floral y frutal, dulzón, complejo",
                            Persistencia = 8.0,
                            Picante = 8.0,
                            RiesgoDominar = "Alto",
                            ScovilleEstimado = "100,000–350,000"
                        },
                        new
                        {
                            Id = 6,
                            Ahumado = 1.0,
                            AporteSalsa = "Sabor sudamericano único; profundidad frutal compleja",
                            ColorPrincipal = "Amarillo-naranja",
                            CombinaCon = "Papa, ajo, cebolla, lima, mariscos",
                            Complejidad = 9.0,
                            DificultadConseguir = "Media",
                            Dulzor = 6.0,
                            FermentaBien = true,
                            Frescura = 6.0,
                            Frutalidad = 7.0,
                            FuncionIdeal = "Personalidad / Aroma",
                            Nombre = "Ají Amarillo",
                            NotasAromaticas = "Fruta seca, floral suave, miel salvaje",
                            PaisRegion = "Perú",
                            PerfilSabor = "Frutal único, floral, levemente terroso, sabor andino inconfundible",
                            Persistencia = 6.0,
                            Picante = 5.0,
                            RiesgoDominar = "Medio",
                            ScovilleEstimado = "30,000–50,000"
                        },
                        new
                        {
                            Id = 7,
                            Ahumado = 2.0,
                            AporteSalsa = "Cuerpo grueso, sabor profundo y complejidad",
                            ColorPrincipal = "Rojo/Naranja intenso",
                            CombinaCon = "Queso, ajo, cebolla, orégano, papa",
                            Complejidad = 8.0,
                            DificultadConseguir = "Media",
                            Dulzor = 5.0,
                            FermentaBien = true,
                            Frescura = 4.0,
                            Frutalidad = 6.0,
                            FuncionIdeal = "Base / Personalidad",
                            Nombre = "Rocoto",
                            NotasAromaticas = "Frutal maduro, especiado, levemente ahumado",
                            PaisRegion = "Perú/Bolivia",
                            PerfilSabor = "Intenso, carnoso, frutal maduro, recuerda al morrón pero picante",
                            Persistencia = 8.0,
                            Picante = 7.0,
                            RiesgoDominar = "Medio",
                            ScovilleEstimado = "50,000–250,000"
                        },
                        new
                        {
                            Id = 8,
                            Ahumado = 1.0,
                            AporteSalsa = "Calor intenso y limpio, rápido",
                            ColorPrincipal = "Rojo/Verde",
                            CombinaCon = "Jengibre, limoncillo, ajo, soja, coco",
                            Complejidad = 5.0,
                            DificultadConseguir = "Fácil",
                            Dulzor = 2.0,
                            FermentaBien = true,
                            Frescura = 7.0,
                            Frutalidad = 3.0,
                            FuncionIdeal = "Picante",
                            Nombre = "Thai Chili / Bird's Eye",
                            NotasAromaticas = "Herbáceo, levemente floral, fresco",
                            PaisRegion = "Tailandia/Asia",
                            PerfilSabor = "Picante rápido y punzante, algo herbáceo, limpio",
                            Persistencia = 7.0,
                            Picante = 7.0,
                            RiesgoDominar = "Medio",
                            ScovilleEstimado = "50,000–100,000"
                        },
                        new
                        {
                            Id = 9,
                            Ahumado = 5.0,
                            AporteSalsa = "Profundidad seca y terrosa; picante sostenido",
                            ColorPrincipal = "Rojo oscuro seco",
                            CombinaCon = "Ajo, tomate, cebolla, vinagre",
                            Complejidad = 6.0,
                            DificultadConseguir = "Fácil",
                            Dulzor = 2.0,
                            FermentaBien = true,
                            Frescura = 3.0,
                            Frutalidad = 2.0,
                            FuncionIdeal = "Picante / Fondo",
                            Nombre = "Chile de Árbol",
                            NotasAromaticas = "Terroso, tostado, algo ahumado",
                            PaisRegion = "México",
                            PerfilSabor = "Seco, terroso, toque de nuez tostada, calor sostenido",
                            Persistencia = 7.0,
                            Picante = 7.0,
                            RiesgoDominar = "Medio",
                            ScovilleEstimado = "15,000–65,000"
                        },
                        new
                        {
                            Id = 10,
                            Ahumado = 4.0,
                            AporteSalsa = "Complejidad y color; sabor tipo mole",
                            ColorPrincipal = "Rojo oscuro",
                            CombinaCon = "Ancho, chipotle, ajo, comino, cacao",
                            Complejidad = 8.0,
                            DificultadConseguir = "Fácil",
                            Dulzor = 5.0,
                            FermentaBien = true,
                            Frescura = 2.0,
                            Frutalidad = 5.0,
                            FuncionIdeal = "Personalidad / Fondo",
                            Nombre = "Guajillo",
                            NotasAromaticas = "Frutal seco, arándano, toffee, tierra",
                            PaisRegion = "México",
                            PerfilSabor = "Suave, frutal seco, arándano, té negro, sin picante dominante",
                            Persistencia = 3.0,
                            Picante = 3.0,
                            RiesgoDominar = "Bajo",
                            ScovilleEstimado = "2,500–5,000"
                        },
                        new
                        {
                            Id = 11,
                            Ahumado = 3.0,
                            AporteSalsa = "Profundidad, dulzor y cuerpo; base perfecta para salsas complejas",
                            ColorPrincipal = "Rojo-café oscuro",
                            CombinaCon = "Mulato, guajillo, chipotle, ajo, comino",
                            Complejidad = 9.0,
                            DificultadConseguir = "Fácil",
                            Dulzor = 7.0,
                            FermentaBien = true,
                            Frescura = 2.0,
                            Frutalidad = 6.0,
                            FuncionIdeal = "Base / Fondo",
                            Nombre = "Ancho (Poblano seco)",
                            NotasAromaticas = "Chocolate, pasas, fruta seca, tierra",
                            PaisRegion = "México",
                            PerfilSabor = "Muy suave, dulce, uva pasa, chocolate, terroso profundo",
                            Persistencia = 2.0,
                            Picante = 2.0,
                            RiesgoDominar = "Bajo",
                            ScovilleEstimado = "1,000–2,000"
                        },
                        new
                        {
                            Id = 12,
                            Ahumado = 10.0,
                            AporteSalsa = "Ahumado potente y profundidad; sabor BBQ premium",
                            ColorPrincipal = "Rojo-café ahumado",
                            CombinaCon = "Ancho, ajo, cebolla, miel, tomate",
                            Complejidad = 8.0,
                            DificultadConseguir = "Fácil",
                            Dulzor = 5.0,
                            FermentaBien = true,
                            Frescura = 2.0,
                            Frutalidad = 3.0,
                            FuncionIdeal = "Aroma / Personalidad",
                            Nombre = "Chipotle (Jalapeño ahumado)",
                            NotasAromaticas = "Humo, madera, caramelo, cuero",
                            PaisRegion = "México",
                            PerfilSabor = "Ahumado BBQ, dulce, terroso, carnoso, maple",
                            Persistencia = 5.0,
                            Picante = 4.0,
                            RiesgoDominar = "Medio-alto",
                            ScovilleEstimado = "5,000–10,000"
                        },
                        new
                        {
                            Id = 13,
                            Ahumado = 1.0,
                            AporteSalsa = "Picante extremo con algo de personalidad frutal",
                            ColorPrincipal = "Rojo/Naranja",
                            CombinaCon = "Mango, zanahoria, habanero, jengibre",
                            Complejidad = 7.0,
                            DificultadConseguir = "Media",
                            Dulzor = 3.0,
                            FermentaBien = true,
                            Frescura = 4.0,
                            Frutalidad = 5.0,
                            FuncionIdeal = "Picante extremo",
                            Nombre = "Ghost Pepper / Bhut Jolokia",
                            NotasAromaticas = "Floral lejano, tierra, algo frutal",
                            PaisRegion = "India",
                            PerfilSabor = "Intenso, frutal, floral tardío pero BRUTAL calor",
                            Persistencia = 10.0,
                            Picante = 9.0,
                            RiesgoDominar = "Muy alto",
                            ScovilleEstimado = "800,000–1,041,427"
                        },
                        new
                        {
                            Id = 14,
                            Ahumado = 1.0,
                            AporteSalsa = "Picante máximo; muy poco más que eso",
                            ColorPrincipal = "Rojo brillante",
                            CombinaCon = "Con mucho habanero/mango para disimular",
                            Complejidad = 5.0,
                            DificultadConseguir = "Difícil",
                            Dulzor = 3.0,
                            FermentaBien = true,
                            Frescura = 2.0,
                            Frutalidad = 4.0,
                            FuncionIdeal = "Picante extremo",
                            Nombre = "Carolina Reaper",
                            NotasAromaticas = "Fruta apenas, luego solo fuego y dolor",
                            PaisRegion = "EE.UU.",
                            PerfilSabor = "Picante nuclear, ligero dulzor frutal antes del apocalipsis",
                            Persistencia = 10.0,
                            Picante = 10.0,
                            RiesgoDominar = "Extremo",
                            ScovilleEstimado = "1,400,000–2,200,000"
                        },
                        new
                        {
                            Id = 15,
                            Ahumado = 1.0,
                            AporteSalsa = "Picante máximo con algo más de complejidad que el Reaper",
                            ColorPrincipal = "Rojo oscuro",
                            CombinaCon = "Habanero, frutas tropicales, zanahoria",
                            Complejidad = 6.0,
                            DificultadConseguir = "Difícil",
                            Dulzor = 3.0,
                            FermentaBien = true,
                            Frescura = 2.0,
                            Frutalidad = 4.0,
                            FuncionIdeal = "Picante extremo",
                            Nombre = "Trinidad Moruga Scorpion",
                            NotasAromaticas = "Floral brevísimo, luego fuego puro",
                            PaisRegion = "Trinidad",
                            PerfilSabor = "Picante extremo, algo floral antes del desastre",
                            Persistencia = 10.0,
                            Picante = 10.0,
                            RiesgoDominar = "Extremo",
                            ScovilleEstimado = "1,200,000–2,009,231"
                        },
                        new
                        {
                            Id = 16,
                            Ahumado = 1.0,
                            AporteSalsa = "Frescura y calor suave; buen cuerpo jugoso",
                            ColorPrincipal = "Amarillo-naranja claro",
                            CombinaCon = "Ajo, cebolla, cilantro, limón",
                            Complejidad = 5.0,
                            DificultadConseguir = "Fácil (Chile)",
                            Dulzor = 4.0,
                            FermentaBien = true,
                            Frescura = 8.0,
                            Frutalidad = 5.0,
                            FuncionIdeal = "Base / Frescura",
                            Nombre = "Ají Cristal",
                            NotasAromaticas = "Fresco, agua de lluvia, leve fruta",
                            PaisRegion = "Chile",
                            PerfilSabor = "Fresco, jugoso, levemente frutal, vegetal agradable",
                            Persistencia = 3.0,
                            Picante = 3.0,
                            RiesgoDominar = "Bajo",
                            ScovilleEstimado = "5,000–30,000"
                        },
                        new
                        {
                            Id = 17,
                            Ahumado = 1.0,
                            AporteSalsa = "Cuerpo y base sin dominar; buen volumen",
                            ColorPrincipal = "Rojo",
                            CombinaCon = "Todo tipo de ingredientes",
                            Complejidad = 4.0,
                            DificultadConseguir = "Fácil (Chile)",
                            Dulzor = 4.0,
                            FermentaBien = true,
                            Frescura = 6.0,
                            Frutalidad = 4.0,
                            FuncionIdeal = "Base",
                            Nombre = "Cacho de Cabra",
                            NotasAromaticas = "Vegetal suave, tierra liviana",
                            PaisRegion = "Chile",
                            PerfilSabor = "Suave, carnoso, algo dulce, muy versátil",
                            Persistencia = 3.0,
                            Picante = 3.0,
                            RiesgoDominar = "Bajo",
                            ScovilleEstimado = "5,000–15,000"
                        },
                        new
                        {
                            Id = 18,
                            Ahumado = 1.0,
                            AporteSalsa = "Carácter chileno intenso y personalidad",
                            ColorPrincipal = "Rojo-naranja",
                            CombinaCon = "Ají cristal, ajo, cebolla, pimentón",
                            Complejidad = 6.0,
                            DificultadConseguir = "Media (Chile)",
                            Dulzor = 3.0,
                            FermentaBien = true,
                            Frescura = 5.0,
                            Frutalidad = 5.0,
                            FuncionIdeal = "Picante / Personalidad",
                            Nombre = "Putaparió",
                            NotasAromaticas = "Frutal breve, luego calor intenso",
                            PaisRegion = "Chile",
                            PerfilSabor = "Intenso, directo, algo frutal y muy picante",
                            Persistencia = 7.0,
                            Picante = 7.0,
                            RiesgoDominar = "Medio-alto",
                            ScovilleEstimado = "50,000–200,000"
                        },
                        new
                        {
                            Id = 19,
                            Ahumado = 1.0,
                            AporteSalsa = "Cuerpo, dulzor y volumen; equilibra mezclas intensas",
                            ColorPrincipal = "Rojo/Amarillo/Verde",
                            CombinaCon = "Todo; excelente para bajar picante",
                            Complejidad = 4.0,
                            DificultadConseguir = "Fácil",
                            Dulzor = 8.0,
                            FermentaBien = true,
                            Frescura = 7.0,
                            Frutalidad = 5.0,
                            FuncionIdeal = "Base / Cuerpo",
                            Nombre = "Morrón / Bell Pepper",
                            NotasAromaticas = "Fruta dulce, vegetal, algo floral",
                            PaisRegion = "Mundial",
                            PerfilSabor = "Dulce, carnoso, vegetal fresco, sin picante",
                            Persistencia = 1.0,
                            Picante = 0.0,
                            RiesgoDominar = "Ninguno",
                            ScovilleEstimado = "0"
                        },
                        new
                        {
                            Id = 20,
                            Ahumado = 3.0,
                            AporteSalsa = "Dulzor, color y cuerpo; similar al morrón",
                            ColorPrincipal = "Rojo/Amarillo",
                            CombinaCon = "Ajo, tomate, cebolla, hierbas",
                            Complejidad = 5.0,
                            DificultadConseguir = "Fácil",
                            Dulzor = 7.0,
                            FermentaBien = true,
                            Frescura = 5.0,
                            Frutalidad = 4.0,
                            FuncionIdeal = "Base",
                            Nombre = "Pimiento Español",
                            NotasAromaticas = "Dulce, ahumado suave, vegetal",
                            PaisRegion = "España",
                            PerfilSabor = "Dulce suave, carnoso, algo ahumado en variedad pimentón",
                            Persistencia = 2.0,
                            Picante = 1.0,
                            RiesgoDominar = "Bajo",
                            ScovilleEstimado = "500–1,000"
                        },
                        new
                        {
                            Id = 21,
                            Ahumado = 3.0,
                            AporteSalsa = "Profundidad tipo mole; complejidad extrema",
                            ColorPrincipal = "Negro-café",
                            CombinaCon = "Mulato, ancho, achiote, ajo, comino",
                            Complejidad = 10.0,
                            DificultadConseguir = "Media",
                            Dulzor = 6.0,
                            FermentaBien = true,
                            Frescura = 2.0,
                            Frutalidad = 4.0,
                            FuncionIdeal = "Fondo / Complejidad",
                            Nombre = "Chihuacle Negro",
                            NotasAromaticas = "Cacao, mole, tierra húmeda, tabaco",
                            PaisRegion = "México",
                            PerfilSabor = "Chocolate oscuro, terroso profundo, ciruela pasa",
                            Persistencia = 3.0,
                            Picante = 3.0,
                            RiesgoDominar = "Bajo",
                            ScovilleEstimado = "1,000–4,000"
                        },
                        new
                        {
                            Id = 22,
                            Ahumado = 3.0,
                            AporteSalsa = "Profundidad mole; complejidad sin picante",
                            ColorPrincipal = "Café-negro",
                            CombinaCon = "Chihuacle, ancho, chipotle, comino",
                            Complejidad = 9.0,
                            DificultadConseguir = "Media",
                            Dulzor = 5.0,
                            FermentaBien = true,
                            Frescura = 2.0,
                            Frutalidad = 4.0,
                            FuncionIdeal = "Fondo / Complejidad",
                            Nombre = "Mulato",
                            NotasAromaticas = "Chocolate amargo, tabaco, tierra",
                            PaisRegion = "México",
                            PerfilSabor = "Similar ancho pero más chocolate y menos dulce, tabaco",
                            Persistencia = 3.0,
                            Picante = 3.0,
                            RiesgoDominar = "Bajo",
                            ScovilleEstimado = "2,500–3,000"
                        },
                        new
                        {
                            Id = 23,
                            Ahumado = 2.0,
                            AporteSalsa = "Complejidad seca; profundidad sin picar",
                            ColorPrincipal = "Café oscuro",
                            CombinaCon = "Guajillo, ancho, ajo, cebolla",
                            Complejidad = 7.0,
                            DificultadConseguir = "Media",
                            Dulzor = 5.0,
                            FermentaBien = true,
                            Frescura = 3.0,
                            Frutalidad = 4.0,
                            FuncionIdeal = "Fondo",
                            Nombre = "Pasilla",
                            NotasAromaticas = "Tierra, fruta seca, hierba seca",
                            PaisRegion = "México",
                            PerfilSabor = "Terroso, uvas pasas, ciruela seca, especiado suave",
                            Persistencia = 2.0,
                            Picante = 2.0,
                            RiesgoDominar = "Bajo",
                            ScovilleEstimado = "1,000–3,000"
                        },
                        new
                        {
                            Id = 24,
                            Ahumado = 1.0,
                            AporteSalsa = "Picante fresco con más dulzor que jalapeño",
                            ColorPrincipal = "Rojo brillante",
                            CombinaCon = "Ajo, cebolla, cilantro, tomate",
                            Complejidad = 5.0,
                            DificultadConseguir = "Fácil",
                            Dulzor = 4.0,
                            FermentaBien = true,
                            Frescura = 7.0,
                            Frutalidad = 5.0,
                            FuncionIdeal = "Picante / Base",
                            Nombre = "Fresno",
                            NotasAromaticas = "Fruta madura, fresco, algo cítrico",
                            PaisRegion = "México/EE.UU.",
                            PerfilSabor = "Similar jalapeño maduro, más frutal y dulce",
                            Persistencia = 4.0,
                            Picante = 5.0,
                            RiesgoDominar = "Bajo",
                            ScovilleEstimado = "2,500–10,000"
                        },
                        new
                        {
                            Id = 25,
                            Ahumado = 1.0,
                            AporteSalsa = "Dulzor, acidez natural y cuerpo",
                            ColorPrincipal = "Amarillo",
                            CombinaCon = "Casi todo; excelente base neutra",
                            Complejidad = 4.0,
                            DificultadConseguir = "Fácil",
                            Dulzor = 6.0,
                            FermentaBien = true,
                            Frescura = 7.0,
                            Frutalidad = 5.0,
                            FuncionIdeal = "Cuerpo / Dulzor",
                            Nombre = "Banana Pepper",
                            NotasAromaticas = "Frutal suave, ácido leve, banana",
                            PaisRegion = "EE.UU./Italia",
                            PerfilSabor = "Dulce, ácido leve, afrutado, casi sin picante",
                            Persistencia = 1.0,
                            Picante = 1.0,
                            RiesgoDominar = "Ninguno",
                            ScovilleEstimado = "0–500"
                        },
                        new
                        {
                            Id = 26,
                            Ahumado = 1.0,
                            AporteSalsa = "Cuerpo y volumen sin alterar perfil",
                            ColorPrincipal = "Verde-amarillo",
                            CombinaCon = "Todo",
                            Complejidad = 3.0,
                            DificultadConseguir = "Fácil",
                            Dulzor = 6.0,
                            FermentaBien = true,
                            Frescura = 8.0,
                            Frutalidad = 4.0,
                            FuncionIdeal = "Base",
                            Nombre = "Cubanelle",
                            NotasAromaticas = "Frutal suave, vegetal fresco",
                            PaisRegion = "Europa/Caribe",
                            PerfilSabor = "Dulce, carnoso, fresco, muy neutro",
                            Persistencia = 1.0,
                            Picante = 1.0,
                            RiesgoDominar = "Ninguno",
                            ScovilleEstimado = "0–1,000"
                        },
                        new
                        {
                            Id = 27,
                            Ahumado = 6.0,
                            AporteSalsa = "Color rojo y profundidad tipo pimentón de la vera",
                            ColorPrincipal = "Rojo oscuro seco",
                            CombinaCon = "Ajo, tomate, romero, pimentón",
                            Complejidad = 7.0,
                            DificultadConseguir = "Media",
                            Dulzor = 6.0,
                            FermentaBien = true,
                            Frescura = 3.0,
                            Frutalidad = 4.0,
                            FuncionIdeal = "Aroma / Fondo",
                            Nombre = "Ñora",
                            NotasAromaticas = "Pimentón ahumado, tierra dulce",
                            PaisRegion = "España",
                            PerfilSabor = "Dulce ahumado, pimentón, profundidad mediterránea",
                            Persistencia = 2.0,
                            Picante = 2.0,
                            RiesgoDominar = "Bajo",
                            ScovilleEstimado = "500–2,500"
                        },
                        new
                        {
                            Id = 28,
                            Ahumado = 2.0,
                            AporteSalsa = "Complejidad mediterránea/oriental única",
                            ColorPrincipal = "Rojo óxido",
                            CombinaCon = "Ajo, limón, cordero, yogur, hierbas",
                            Complejidad = 8.0,
                            DificultadConseguir = "Difícil",
                            Dulzor = 5.0,
                            FermentaBien = true,
                            Frescura = 4.0,
                            Frutalidad = 5.0,
                            FuncionIdeal = "Personalidad / Aroma",
                            Nombre = "Aleppo",
                            NotasAromaticas = "Fruta seca, cuero, aceite, sal",
                            PaisRegion = "Siria/Turquía",
                            PerfilSabor = "Frutal, aceite de oliva, cuero, sal, picante tardío",
                            Persistencia = 4.0,
                            Picante = 3.0,
                            RiesgoDominar = "Medio",
                            ScovilleEstimado = "10,000"
                        },
                        new
                        {
                            Id = 29,
                            Ahumado = 7.0,
                            AporteSalsa = "Umami y complejidad extrema; muy particular",
                            ColorPrincipal = "Café-negro-púrpura",
                            CombinaCon = "Ajo, cebolla caramelizada, berenjena, carne",
                            Complejidad = 9.0,
                            DificultadConseguir = "Difícil",
                            Dulzor = 7.0,
                            FermentaBien = true,
                            Frescura = 2.0,
                            Frutalidad = 5.0,
                            FuncionIdeal = "Aroma / Umami",
                            Nombre = "Urfa Biber",
                            NotasAromaticas = "Cacao, humo, tierra, aceite",
                            PaisRegion = "Turquía",
                            PerfilSabor = "Ahumado, chocolate negro, pasas, aceite, umami profundo",
                            Persistencia = 3.0,
                            Picante = 3.0,
                            RiesgoDominar = "Bajo",
                            ScovilleEstimado = "7,000–8,000"
                        },
                        new
                        {
                            Id = 30,
                            Ahumado = 1.0,
                            AporteSalsa = "Color rojo profundo con poco picante",
                            ColorPrincipal = "Rojo brillante intenso",
                            CombinaCon = "Yogur, especias indias, jengibre, ajo",
                            Complejidad = 4.0,
                            DificultadConseguir = "Difícil",
                            Dulzor = 4.0,
                            FermentaBien = true,
                            Frescura = 4.0,
                            Frutalidad = 3.0,
                            FuncionIdeal = "Color / Aroma",
                            Nombre = "Kashmiri",
                            NotasAromaticas = "Suave, frutal leve, tierra",
                            PaisRegion = "India",
                            PerfilSabor = "Suave, colorante intenso, algo frutal seco",
                            Persistencia = 2.0,
                            Picante = 3.0,
                            RiesgoDominar = "Bajo",
                            ScovilleEstimado = "1,000–2,000"
                        },
                        new
                        {
                            Id = 31,
                            Ahumado = 1.0,
                            AporteSalsa = "Carácter africano/portugués; picante cítrico",
                            ColorPrincipal = "Rojo",
                            CombinaCon = "Limón, ajo, cebolla, hierbas, aceite oliva",
                            Complejidad = 6.0,
                            DificultadConseguir = "Media",
                            Dulzor = 3.0,
                            FermentaBien = true,
                            Frescura = 7.0,
                            Frutalidad = 4.0,
                            FuncionIdeal = "Picante / Personalidad",
                            Nombre = "Piri Piri / African Bird",
                            NotasAromaticas = "Cítrico, herbáceo, levemente frutal",
                            PaisRegion = "África/Portugal",
                            PerfilSabor = "Picante ácido, cítrico, limpio y directo",
                            Persistencia = 7.0,
                            Picante = 7.0,
                            RiesgoDominar = "Medio",
                            ScovilleEstimado = "50,000–175,000"
                        },
                        new
                        {
                            Id = 32,
                            Ahumado = 2.0,
                            AporteSalsa = "Sabor seco y profundo tipo asiático",
                            ColorPrincipal = "Rojo oscuro seco",
                            CombinaCon = "Comino, cilantro, ajo, jengibre",
                            Complejidad = 6.0,
                            DificultadConseguir = "Difícil",
                            Dulzor = 4.0,
                            FermentaBien = true,
                            Frescura = 4.0,
                            Frutalidad = 5.0,
                            FuncionIdeal = "Fondo / Picante",
                            Nombre = "Dundicut",
                            NotasAromaticas = "Frutal seco, tierra, algo dulce",
                            PaisRegion = "Pakistán",
                            PerfilSabor = "Frutal, terroso, calor sostenido",
                            Persistencia = 6.0,
                            Picante = 7.0,
                            RiesgoDominar = "Medio",
                            ScovilleEstimado = "55,000–65,000"
                        },
                        new
                        {
                            Id = 33,
                            Ahumado = 5.0,
                            AporteSalsa = "Similar chile de árbol pero más oscuro y profundo",
                            ColorPrincipal = "Muy oscuro",
                            CombinaCon = "Ajo, tomate, cebolla, chipotle",
                            Complejidad = 6.0,
                            DificultadConseguir = "Media",
                            Dulzor = 2.0,
                            FermentaBien = true,
                            Frescura = 3.0,
                            Frutalidad = 2.0,
                            FuncionIdeal = "Fondo / Picante",
                            Nombre = "Árbol Negro",
                            NotasAromaticas = "Nuez, tostado, tierra oscura",
                            PaisRegion = "México",
                            PerfilSabor = "Terroso oscuro, nuez tostada, algo ahumado",
                            Persistencia = 6.0,
                            Picante = 6.0,
                            RiesgoDominar = "Medio",
                            ScovilleEstimado = "15,000–30,000"
                        },
                        new
                        {
                            Id = 34,
                            Ahumado = 1.0,
                            AporteSalsa = "Acidez y frescura; carácter mediterráneo",
                            ColorPrincipal = "Rojo/Verde",
                            CombinaCon = "Aceitunas, ajo, vinagre, hierbas",
                            Complejidad = 4.0,
                            DificultadConseguir = "Fácil",
                            Dulzor = 4.0,
                            FermentaBien = true,
                            Frescura = 7.0,
                            Frutalidad = 3.0,
                            FuncionIdeal = "Acidez / Frescura",
                            Nombre = "Pepperoncini",
                            NotasAromaticas = "Ácido, briny, fresco, leve cítrico",
                            PaisRegion = "Italia/Grecia",
                            PerfilSabor = "Ácido, levemente picante, fresco, en vinagre",
                            Persistencia = 1.0,
                            Picante = 1.0,
                            RiesgoDominar = "Bajo",
                            ScovilleEstimado = "100–500"
                        },
                        new
                        {
                            Id = 35,
                            Ahumado = 1.0,
                            AporteSalsa = "Jalapeño más suave; buen cuerpo",
                            ColorPrincipal = "Verde/Rojo",
                            CombinaCon = "Ajo, cebolla, tomate, cilantro",
                            Complejidad = 4.0,
                            DificultadConseguir = "Fácil",
                            Dulzor = 4.0,
                            FermentaBien = true,
                            Frescura = 7.0,
                            Frutalidad = 4.0,
                            FuncionIdeal = "Base",
                            Nombre = "Cuaresmeño",
                            NotasAromaticas = "Vegetal dulce, fresco, algo frutal",
                            PaisRegion = "México",
                            PerfilSabor = "Similar jalapeño pero más suave, carnoso y dulzón",
                            Persistencia = 3.0,
                            Picante = 4.0,
                            RiesgoDominar = "Bajo",
                            ScovilleEstimado = "5,000–15,000"
                        },
                        new
                        {
                            Id = 36,
                            Ahumado = 1.0,
                            AporteSalsa = "Sabor tropical andino particular",
                            ColorPrincipal = "Amarillo-naranja",
                            CombinaCon = "Mango, piña, habanero, jengibre",
                            Complejidad = 7.0,
                            DificultadConseguir = "Difícil",
                            Dulzor = 6.0,
                            FermentaBien = true,
                            Frescura = 6.0,
                            Frutalidad = 8.0,
                            FuncionIdeal = "Personalidad / Aroma",
                            Nombre = "Amarillo Mango",
                            NotasAromaticas = "Mango, limón, floral tropical",
                            PaisRegion = "Perú",
                            PerfilSabor = "Mango, cítrico, floral suave, tropical andino",
                            Persistencia = 5.0,
                            Picante = 5.0,
                            RiesgoDominar = "Medio",
                            ScovilleEstimado = "25,000–40,000"
                        });
                });

            modelBuilder.Entity("SalsaSimulator.Models.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComposicionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiasFerrmentacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsPeligrosa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ingredientes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NotasSabor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Picante")
                        .HasColumnType("REAL");

                    b.Property<string>("ResultadoEsperado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Builds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComposicionJson = "[{\"nombre\":\"Habanero\",\"porcentaje\":40},{\"nombre\":\"Zanahoria\",\"porcentaje\":15},{\"nombre\":\"Cebolla morada\",\"porcentaje\":10}]",
                            DiasFerrmentacion = 5,
                            Emoji = "🌴",
                            EsPeligrosa = false,
                            Ingredientes = "Habanero 40% + Mango 20% + Piña 10% + Zanahoria 15% + Ajo 5% + Cebolla morada 10%",
                            Nombre = "Tropical Gourmet",
                            NotasSabor = "Tropical explosivo, frutal, dulce-picante, floral, naranja intenso",
                            Picante = 7.0,
                            ResultadoEsperado = "Naranja brillante, textura media, dulzor tropical equilibrado con calor habanero.",
                            Slug = "tropical-gourmet"
                        },
                        new
                        {
                            Id = 2,
                            ComposicionJson = "[{\"nombre\":\"Jalapeño\",\"porcentaje\":40},{\"nombre\":\"Serrano\",\"porcentaje\":30},{\"nombre\":\"Tomate\",\"porcentaje\":15}]",
                            DiasFerrmentacion = 4,
                            Emoji = "🇲🇽",
                            EsPeligrosa = false,
                            Ingredientes = "Jalapeño 40% + Serrano 30% + Tomate verde 15% + Ajo 10% + Cilantro 5%",
                            Nombre = "Mexicana Verde",
                            NotasSabor = "Verde fresco, herbáceo, cítrico, limpio, vegetal",
                            Picante = 5.0,
                            ResultadoEsperado = "Verde brillante, textura semilíquida, frescura total.",
                            Slug = "mexicana-verde"
                        },
                        new
                        {
                            Id = 3,
                            ComposicionJson = "[{\"nombre\":\"Cayena / Cayenne\",\"porcentaje\":30},{\"nombre\":\"Jalapeño\",\"porcentaje\":30},{\"nombre\":\"Zanahoria\",\"porcentaje\":20}]",
                            DiasFerrmentacion = 6,
                            Emoji = "🔴",
                            EsPeligrosa = false,
                            Ingredientes = "Cayena 30% + Jalapeño rojo 30% + Zanahoria 20% + Tomate 10% + Ajo 10%",
                            Nombre = "Roja Balanceada",
                            NotasSabor = "Rojo clásico, equilibrado, picante moderado, versátil",
                            Picante = 5.0,
                            ResultadoEsperado = "Rojo brillante, textura media, all-purpose.",
                            Slug = "roja-balanceada"
                        },
                        new
                        {
                            Id = 4,
                            ComposicionJson = "[{\"nombre\":\"Habanero\",\"porcentaje\":35}]",
                            DiasFerrmentacion = 3,
                            Emoji = "🥭",
                            EsPeligrosa = false,
                            Ingredientes = "Habanero 35% + Mango 35% + Cebolla morada 15% + Lima 10% + Sal 5%",
                            Nombre = "Mango Habanero",
                            NotasSabor = "Frutal-tropical intenso, dulce y feroz al mismo tiempo",
                            Picante = 8.0,
                            ResultadoEsperado = "Naranja tropical, textura líquida-media, dulzor + calor extremo.",
                            Slug = "mango-habanero"
                        },
                        new
                        {
                            Id = 5,
                            ComposicionJson = "[{\"nombre\":\"Chipotle (Jalapeño ahumado)\",\"porcentaje\":50},{\"nombre\":\"Ancho (Poblano seco)\",\"porcentaje\":20},{\"nombre\":\"Chile de Árbol\",\"porcentaje\":15}]",
                            DiasFerrmentacion = 7,
                            Emoji = "🔥",
                            EsPeligrosa = false,
                            Ingredientes = "Chipotle 50% + Ancho 20% + Chile de Árbol 15% + Ajo 10% + Miel 5%",
                            Nombre = "Ahumada BBQ",
                            NotasSabor = "Ahumado profundo, BBQ, dulzor caramelizado, terroso",
                            Picante = 5.0,
                            ResultadoEsperado = "Café-rojo oscuro, espesa, ahumado dominante.",
                            Slug = "ahumada-bbq"
                        },
                        new
                        {
                            Id = 6,
                            ComposicionJson = "[{\"nombre\":\"Cayena / Cayenne\",\"porcentaje\":50},{\"nombre\":\"Jalapeño\",\"porcentaje\":20}]",
                            DiasFerrmentacion = 7,
                            Emoji = "🎷",
                            EsPeligrosa = false,
                            Ingredientes = "Cayena 50% + Jalapeño 20% + Vinagre blanco 20% + Sal 10%",
                            Nombre = "Estilo Louisiana",
                            NotasSabor = "Ácido, picante, limpio, directo — estilo Tabasco/Frank's",
                            Picante = 6.0,
                            ResultadoEsperado = "Rojo brillante, muy líquida, ácida y picante.",
                            Slug = "louisiana"
                        },
                        new
                        {
                            Id = 7,
                            ComposicionJson = "[{\"nombre\":\"Serrano\",\"porcentaje\":40},{\"nombre\":\"Jalapeño\",\"porcentaje\":25}]",
                            DiasFerrmentacion = 3,
                            Emoji = "🟢",
                            EsPeligrosa = false,
                            Ingredientes = "Serrano 40% + Jalapeño 25% + Lima (jugo) 20% + Cebolla 10% + Ajo 5%",
                            Nombre = "Verde Cítrica",
                            NotasSabor = "Cítrico, fresco, verde, limpio con buena acidez",
                            Picante = 5.0,
                            ResultadoEsperado = "Verde-amarillo, líquida, refrescante.",
                            Slug = "verde-citrica"
                        },
                        new
                        {
                            Id = 8,
                            ComposicionJson = "[{\"nombre\":\"Cayena / Cayenne\",\"porcentaje\":30},{\"nombre\":\"Jalapeño\",\"porcentaje\":20}]",
                            DiasFerrmentacion = 8,
                            Emoji = "🧄",
                            EsPeligrosa = false,
                            Ingredientes = "Cayena 30% + Jalapeño 20% + Ajo 30% + Vinagre manzana 15% + Cebolla 5%",
                            Nombre = "Garlic Bomb",
                            NotasSabor = "Ajo dominante, picante medio, acidez suave, aromática intensa",
                            Picante = 5.0,
                            ResultadoEsperado = "Rojo-dorado, media, sabor a ajo fermentado extremadamente aromático.",
                            Slug = "garlic-bomb"
                        },
                        new
                        {
                            Id = 9,
                            ComposicionJson = "[{\"nombre\":\"Chipotle (Jalapeño ahumado)\",\"porcentaje\":25},{\"nombre\":\"Ancho (Poblano seco)\",\"porcentaje\":20},{\"nombre\":\"Chile de Árbol\",\"porcentaje\":15}]",
                            DiasFerrmentacion = 10,
                            Emoji = "🍄",
                            EsPeligrosa = false,
                            Ingredientes = "Chipotle 25% + Ancho 20% + Chile de Árbol 15% + Tomate 20% + Ajo 15% + Cebolla 5%",
                            Nombre = "Umami Profunda",
                            NotasSabor = "Umami profundo, terroso, ahumado, complejo como un mole",
                            Picante = 4.0,
                            ResultadoEsperado = "Café oscuro muy espesa, umami extremo.",
                            Slug = "umami-profunda"
                        },
                        new
                        {
                            Id = 10,
                            ComposicionJson = "[{\"nombre\":\"Carolina Reaper\",\"porcentaje\":30},{\"nombre\":\"Ghost Pepper / Bhut Jolokia\",\"porcentaje\":30},{\"nombre\":\"Trinidad Moruga Scorpion\",\"porcentaje\":20},{\"nombre\":\"Habanero\",\"porcentaje\":20}]",
                            DiasFerrmentacion = 5,
                            Emoji = "☢️",
                            EsPeligrosa = true,
                            Ingredientes = "Carolina Reaper 30% + Ghost Pepper 30% + Trinidad Scorpion 20% + Habanero 20%",
                            Nombre = "Nuclear",
                            NotasSabor = "Solo picante. SOLO PICANTE.",
                            Picante = 10.0,
                            ResultadoEsperado = "Rojo intenso, líquida, picante más allá del dolor.",
                            Slug = "nuclear"
                        },
                        new
                        {
                            Id = 11,
                            ComposicionJson = "[{\"nombre\":\"Carolina Reaper\",\"porcentaje\":40},{\"nombre\":\"Trinidad Moruga Scorpion\",\"porcentaje\":40},{\"nombre\":\"Chile de Árbol\",\"porcentaje\":20}]",
                            DiasFerrmentacion = 3,
                            Emoji = "😭",
                            EsPeligrosa = true,
                            Ingredientes = "Carolina Reaper 40% + Trinidad Scorpion 40% + Chile de árbol 20%",
                            Nombre = "Criminal de Guerra",
                            NotasSabor = "Destrucción total de papilas. No hay sabor, solo fuego eterno.",
                            Picante = 10.0,
                            ResultadoEsperado = "⚠️ PELIGRO BIOLÓGICO. Rojo sangre. Esta salsa es un arma.",
                            Slug = "criminal-de-guerra"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
